apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prod
spec:
  url: https://github.com/AndresRCB/fluxdemo
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod
spec:
  sourceRef:
    kind: GitRepository
    name: prod
  path: cluster-config/apps/production